- job:
    name: build
    description: 'This job builds Maxscale'
    parameters: 
      - !include: './maxscale_jobs/include/value.yaml'
      - !include: './maxscale_jobs/include/source.yaml'
      - choice:
          name: box
          choices:
            !include: './maxscale_jobs/include/boxes.yaml'
      - !include: './maxscale_jobs/include/target.yaml'
      - !include: './maxscale_jobs/include/remove_strip.yaml'
      - !include: './maxscale_jobs/include/cmake_flags.yaml'
      - !include: './maxscale_jobs/include/do_not_destroy_vm.yaml'
      - !include: './maxscale_jobs/include/coverity.yaml'
      - !include: './maxscale_jobs/include/build_experimental.yaml'
      - !include: './maxscale_jobs/include/use_mariadbd.yaml'
      - !include: './maxscale_jobs/include/repo_path.yaml'
      - !include: './maxscale_jobs/include/try_already_running.yaml'
    scm:
      - git:
          url: !include: './maxscale_jobs/include/maxscale_repo.yaml'
          branches:
            - 'develop'
    builders:
      - shell: 
          '$HOME/build-scripts/prepare_and_build.sh'
    publishers:
      - !include: './maxscale_jobs/include/mail.yaml'
      - !include: './maxscale_jobs/include/call_cleanup_at_build.yaml'
    wrappers:
      - workspace-cleanup:
          include:
            - "*.*"
          dirmatch: true
    concurrent: true
